pizzapanucci/authorization/urls.py
from django.urls import path

from . import views

app_name = 'authorization'

urlpatterns = [

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('restore_password/', views.restore_password, name='restore_password'),
    path('registration/', views.registration, name='registration'),
    path('result/', views.result, name='result')
]

pizzapanucci/pizzapanucci/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static


urlpatterns = [

    path('authorization/', include('authorization.urls')),
    path('store/', include('store.urls')),
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
]

pizzapanucci/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [

    path('', views.index, name='index'),
    path('cart/', views.cart, name='index'),
    path('order/', views.order, name='order'),
    path('order_success/', views.order_success, name='order_success')
]

pizzapanucci/authorization/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=100)
    password_hash = models.CharField(max_length=128)

pizzapanucci/store/models.py
from django.db import models
from django.contrib.auth.models import User


class FoodType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Plate(models.Model):

    name = models.CharField(max_length=100)
    small_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    big_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    type_id = models.ForeignKey(FoodType, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class FoodAddition(models.Model):

    name = models.CharField(max_length=100)
    small_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    big_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    plate_id = models.ForeignKey(Plate, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Orders(models.Model):

    id_user = models.IntegerField()
    cart = models.TextField()

    def __str__(self):
        return 'id user: ' + str(self.id_user) + ' cart: ' + str(self.cart)

pizzapanucci/authorization/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User


def login(request):

    if request.user.is_authenticated:
        from django.conf import settings
        return redirect('%s?next=%s' % (reverse('store:index'), request.path))

    if request.method == 'POST':

        from django.contrib.auth import authenticate, login

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:

            login(request, user)

            return HttpResponseRedirect(reverse('store:index'))

        else:
            return render(request, 'authorization/result.html', {'message': 'bad credentials'})

    return render(request, 'authorization/login.html', {})


def logout(request):

    from django.contrib.auth import logout

    logout(request)
    return HttpResponseRedirect(reverse('store:index'))


def registration(request):
    context = {}

    if request.method == 'POST':

        if len(User.objects.filter(username=request.POST['username'])) > 0:

            context['message'] = 'username is busy'

            return render(request, 'authorization/result.html', context)

        else:

            user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
            user.save()

            context['message'] = 'success registration'

            return render(request, 'authorization/result.html', context)

    return render(request, 'authorization/registration.html', {'request': request})


def restore_password(request):
    return render(request, 'authorization/restore_password.html', {})


def result(request):
    return render(request, 'authorization/result.html', {})

pizzapanucci/store/views.py
from django.shortcuts import render, redirect, reverse

from .models import FoodType, Plate, FoodAddition, Orders


def index(request):

    return render(request, 'store/index.html', {'menu': get_menu()})


def cart(request):

    if request.user.is_authenticated:

        return render(request, 'store/cart.html', {})

    else:
        return redirect(request, reverse('authorization:login'))


def order(request):

    if request.method == 'POST':
        user = request.user
        new_order = Orders(None, user.id, request.POST['order'])
        new_order.save()
        return render(request, 'store/order_success.html')

    return redirect(request, reverse('store:index'))


def order_success(request):
    return render(request, 'store/order_success.html')


def get_menu():

    return {type.id:
                 {'name': type.name, 'plates': [
                     {'name': plate.name, 'id': plate.id, 'itself': plate,
                      'additions': [
                              addition for addition in FoodAddition.objects.filter(plate_id=plate.id)
                        ]
                      }
                     for plate in Plate.objects.filter(type_id=type.id)] }
             for type in FoodType.objects.all()}

pizzapanucci/authorization/templates/authorization/login.html
{% extends '../authorization_base.html' %}

{% block content %}

<h1>Login page</h1>

<p>{{ user }}</p>

<form action="{% url 'authorization:login' %}" method="post">

    {% csrf_token %}

    <table>
        <tr>
            <td>
                <label>Username</label>
            </td>
            <td>
                <input type="text" name="username" />
            </td>
        </tr>
        <tr>
            <td>
                <label>Password</label>
            </td>
            <td>
                <input type="password" name="password">
            </td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit"></td>
        </tr>
    </table>

</form>

{% endblock %}

pizzapanucci/authorization/templates/authorization/registration.html
{% extends '../authorization_base.html' %}

{% block content %}

<h1>Registration</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'authorization:registration' %}" method="post">

    {% csrf_token %}

    <label>Username</label>
    <input type="text" name="username" required>
    <br>
    <label>Password</label>
    <input type="password" name="password" required>

    <input type="submit">

</form>

{% endblock %}

pizzapanucci/authorization/templates/authorization/restore_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>restore_password module</p>
</body>
</html>

pizzapanucci/authorization/templates/authorization/result.html
{% extends '../authorization_base.html' %}

{% block content %}
{{ message }}
{% endblock %}

pizzapanucci/authorization/templates/authorization_base.html
{% extends 'base.html' %}

pizzapanucci/pizzapanucci/templates/pizzapanucci/admin/base_site.html
{% extends "admin/base.html" %}

{% block title %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Pizza panucci admin</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

pizzapanucci/pizzapanucci/templates/pizzapanucci/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" src="{% static "pizzapanucci/style.css" %}">
    <title>{% block title %}Pizza panucci{% endblock %}</title>

    <script>

    let cart = {0: {'total_price': 0}};
    let totalView = undefined;

    function plateClick(plate){

        let dbId = +plate.attributes[1].value;

        let price = +plate.attributes[4].value;
        let name = plate.attributes[5].value;

        cart[dbId] = {};

        cart[dbId].name = name;
        cart[dbId].price = price;
        cart[dbId].additions = [];

        cart[0].total_price += price;

        localStorage.setItem('cart', JSON.stringify(cart));
        updateTotal();
    }

    function additionClick(addition, plateId){

        plateId = +plateId;

        for(let plate in cart){

            plate = +plate;

            if(plate === plateId){

                let name = addition.attributes[5].value;
                let dbId = +addition.attributes[1].value;
                let price = +addition.attributes[4].value;

                cart[plate].additions.push({id: dbId, price: price, name: name});
                cart[0]['total_price'] += price;

                localStorage.setItem('cart', JSON.stringify(cart));
                updateTotal();
                return;
            }
        }

    }

    function initCart(){

        let localStorageCart = localStorage.getItem('cart');

        if(typeof localStorageCart === 'string' && localStorageCart !== 'null'
            && localStorageCart.length > 0 && JSON.stringify(cart).length <= 23){

            cart = JSON.parse(localStorageCart);
        }
    }

    function updateTotal(){

        if(typeof totalView !== 'undefined'){
            totalView.innerHTML = cart[0].total_price.toFixed(2);
        }
    }

    document.addEventListener('DOMContentLoaded', function(){

        totalView = document.getElementById('total-view');

        initCart();
        updateTotal();
    });

    {% block custom_script %}
    {% endblock %}
    </script>

    <style>

    {% block custom_style %}
    {% endblock %}
    </style>

</head>

<body>
    <div id="sidebar">
        {% block sidebar %}

        {% if user.is_authenticated %}
            <p>Hello {{ user.username }}&nbsp;&nbsp;<a href="/authorization/logout">Sign Out</a></p>

            <p>
                <a href="/store/cart/">Shopping cart</a>
                &nbsp;
                <span id="total-view"></span>
            </p>
        {% else %}
            <ul>
                <li><a href="/authorization/login">Sign In</a></li>
                <li><a href="/authorization/registration">Sign Up</a></li>
            </ul>
        {% endif %}
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

pizzapanucci/store/templates/store/cart.html
{% extends '../store_base.html %}

{% block content %}

<script>

    document.addEventListener('DOMContentLoaded', function(){
        let cartPositions = document.getElementById('cart-positions');
        let jsonCart = localStorage.getItem('cart');
        let localCart = JSON.parse(jsonCart);
        let cartValue = document.getElementById('cart_value');

        cartValue.value = jsonCart;

        if(typeof localCart !== 'undefined'){

            for(let item in localCart){

                if(item === '0'){
                    continue;
                }

                let tr = document.createElement('tr');
                let td1 = document.createElement('td');
                let td2 = document.createElement('td');

                td1.innerHTML = localCart[item].name;
                td2.innerHTML = localCart[item].price + '$';

                tr.appendChild(td1);
                tr.appendChild(td2);

                cartPositions.appendChild(tr);

                for(let addition in localCart[item].additions){

                    let tr = document.createElement('tr');
                    let td1 = document.createElement('td');
                    let td2 = document.createElement('td');

                    td1.innerHTML = '+&nbsp;' + localCart[item].additions[addition].name;
                    td2.innerHTML = localCart[item].additions[addition].price + '$';

                    tr.appendChild(td1);
                    tr.appendChild(td2);

                    cartPositions.appendChild(tr);
                }

            }

            let tr = document.createElement('tr');
            let td1 = document.createElement('td');
            let td2 = document.createElement('td');

            td1.innerHTML = 'total: ';
            td2.innerHTML = cart[0]['total_price'].toFixed(2) + '$';

            tr.appendChild(td1);
            tr.appendChild(td2);

            cartPositions.appendChild(tr);

        }
    });

</script>

<table id="cart-positions">
    <tr>
        <th>
            Name
        </th>
        <th>
            Price
        </th>
    </tr>
</table>

<form action="{% url 'store:order' %}" method="post">

    {% csrf_token %}

    <input type="hidden" name="order" id="cart_value">

    <input type="submit">
</form>


{% endblock %}

pizzapanucci/store/templates/store/change_form.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script type="text/javascript" src="{% static 'store/formset_handlers.js' %}"></script>
{% endblock %}

pizzapanucci/store/templates/store/index.html
{% extends '../store_base.html' %}

{% block custom_script %}
{% endblock %}

{% block custom_style %}

.menu-item{

cursor: pointer;
border-bottom: 1px dotted blue;
color: blue;
}

{% endblock %}


{% block content %}

<table>
    <tr>
        <th>
            Item
        </th>
        <th>
            Small
        </th>
        <th>
            Big
        </th>
    </tr>
    {% for k, v in menu.items %}
    <tr>
        <td colspan="3">
            <b>{{ v.name }}</b>
        </td>
    </tr>


    {% for plate in v.plates %}
    <tr>
        <td>
            {{ plate.name }}
        </td>
        <td>
            {% if plate.itself.small_price > 0%}
            <span class="menu-item" data-id="{{ plate.id }}" data-food-type="plate"
                  onclick="plateClick(this)"
                  data-price="{{ plate.itself.small_price }}" data-name="{{ plate.name }}">{{ plate.itself.small_price }}$</span>
            {% endif %}
        </td>
        <td>
            {% if plate.itself.big_price > 0 %}
            <span class="menu-item" data-id="{{ plate.id }}" data-food-type="plate"
                  onclick="plateClick(this)"
                  data-price="{{ plate.itself.big_price }}" data-name="{{ plate.name }}">{{ plate.itself.big_price }}$</span>
            {% endif %}
        </td>

    </tr>

    {% for addition in plate.additions %}
    <tr>
        {% if forloop.first %}

        {% endif %}
        <td>

            +&nbsp;&nbsp;{{ addition.name }}
        </td>
        <td>
            <span class="menu-item" data-id="{{ addition.id }}" data-food-type="addition"
                  onclick="additionClick(this, {{ plate.id }})"
                  data-price="{{ addition.small_price }}" data-name="{{ addition.name }}">{{ addition.small_price }}$</span>
        </td>
        <td>
            <span class="menu-item" data-id="{{ addition.id }}" data-food-type="addition"
                  onclick="additionClick(this, {{ plate.id }})"
                  data-price="{{ addition.big_price }}" data-name="{{ addition.name }}">{{ addition.big_price }}$</span>
        </td>

        {% if forloop.last %}

        {% endif %}
    </tr>
    {% endfor %}

    {% endfor %}

    {% endfor %}
</table>

{% endblock %}

pizzapanucci/store/templates/store/index_ul.html
{% extends '../store_base.html' %}

{% block custom_script %}
{% endblock %}

{% block custom_style %}

.menu-item{

    cursor: pointer;
    border-bottom: 1px dotted blue;
    color: blue;
}

{% endblock %}


{% block content %}

<ul>
{% for k, v in menu.items %}

    <b>{{ v.name }}</b>

    {% for plate in v.plates %}

        <li>
            <span class="menu-item" data-id="{{ plate.id }}" data-food-type="plate"
                  onclick="plateClick(this)" data-small-price="{{ plate.itself.small_price }}"
                  data-big-price="{{ plate.itself.big_price }}">{{ plate.name }}</span>
            <span class="menu-item">small: {{ plate.itself.small_price }}</span>
            <span class="menu-item">small: {{ plate.itself.big_price }}</span>
        </li>

        {% for addition in plate.additions %}

            {% if forloop.first %}
                <ul>
            {% endif %}
                    <li>
                        <span class="menu-item" data-id="{{ addition.id }}" data-food-type="addition"
                              onclick="additionClick(this, {{ plate.id }})" data-small-price="{{ addition.small_price }}"
                              data-big-price="{{ addition.big_price }}">{{ addition.name }}
                        </span>
                    </li>
            {% if forloop.last %}
                </ul>
            {% endif %}

        {% endfor %}

    {% endfor %}

{% endfor %}
</ul>

{% endblock %}

pizzapanucci/store/templates/store/order_success.html
{% extends '../store_base.html %}

{% block content %}
    <script>

        localStorage.setItem('cart', null);

    </script>
    <p>Order placed!</p>

{% endblock %}

pizzapanucci/store/templates/store_base.html
{% extends 'base.html' %}